object Versions {

    const val coil: String = "2.2.0"
    const val splashScreen: String = "1.0.0"
    const val navigationCompose: String = "2.7.6"
    const val coroutines: String = "1.7.3"
    const val retrofit: String = "2.9.0"
    const val okhttp: String = "5.0.0-alpha.2"
    const val gsonConverter: String = "2.9.0"
    const val moshi: String = "1.13.0"
    const val moshiConverter: String = "2.9.0"
    const val loggingInterceptor: String = "4.8.1"
    const val hiltNavigationCompose: String = "1.0.0"
    const val hilt: String = "2.48"
    const val hiltCompiler: String = "1.1.0-alpha01"
    const val material: String = "1.11.0"
    const val appCompat: String = "1.6.1"
    const val testEspresso: String = "3.5.1"
    const val testJunit: String = "1.1.5"
    const val junit: String = "4.13.2"
    const val composeBom: String = "2023.08.00"
    const val coreKtx = "1.12.0"
    const val activityCompose = "1.8.2"
}